on: pull_request

jobs:
  job1:
    runs-on: 'ubuntu-latest'
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - run: 'echo "${{ github.event.pull_request.title }}"'
          
